version: '3'
services:
    app:
        build: .
        command: node build/main.js
        environment:
            - BOT_TOKEN=${BOT_TOKEN}
            - DISCORD_APP_ID=${DISCORD_APP_ID}
            - SUPABASE_KEY=${SUPABASE_KEY}
            - SUPABASE_URL=${SUPABASE_URL}
